name: apevolo_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
    sdk: '>=3.2.3 <4.0.0'

dependencies:
    cupertino_icons: ^1.0.2
    fluentui_system_icons: ^1.1.226
    get: 4.6.6
    crypto: ^3.0.3
    pointycastle: ^3.7.4
    encrypt: ^5.0.3
    dio: ^5.4.1
    get_storage: ^2.1.1
    darq: 2.0.0
    flutter:
        sdk: flutter
    flutter_localization: ^0.2.0

dev_dependencies:
    flutter_lints: ^2.0.0
    flutter_test:
        sdk: flutter

flutter:
    assets:
        - assets/certificate/
    uses-material-design: true
